# testing shit
branches: ['main', 'semver']
ci: true
plugins:
- '@semantic-release/commit-analyzer'
- '@semantic-release/release-notes-generator'
- - '@semantic-release/npm'
  - npmPublish: false
- '@semantic-release/git'
analyzeCommits:
  - path: '@semantic-release/commit-analyzer'
    releaseRules:
    - type: 'feat'
      release: 'minor'
    - type: 'fix'
      release: 'patch'
    - type: 'patch'
      release: 'patch'
    - type: 'minor'
      release: 'minor'
    - type: 'breaking'
      release: 'major'
    - type: 'major'
      release: 'major'