# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: "*"
  pull_request:
    branches: [ "main" ]

env: 
  branch_name: ${{ github.ref_name }}
  build_number: ${{ github.run_number }}

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    # - run: echo ${{ github.ref_name }}
    - run: npm i
    - run: npm run build --if-present
    - name: Build and Push Docker Image
      uses: mr-smithers-excellent/docker-build-push@v4
      with:
        image: eladpress/elad-press
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tag: "${{ env.branch_name }}-${{env.build_number}}"
    - name: setup semantic-release
      run: npm install -g semantic-release @semantic-release/git @semantic-release/changelog @eladpress/semantic-release-gitflow -D
    - name: release
      run: npx semantic-release
    - name: check something
      run: cat package.json
      
